// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.126 Production Release
//  HLS Date:       Wed Aug  8 00:52:07 PDT 2012
// 
//  Generated by:   fyq14@EEWS104A-012
//  Generated date: Fri May 01 17:16:35 2015
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    edge_counter_core_fsm
//  FSM Module
// ------------------------------------------------------------------


module edge_counter_core_fsm (
  clk, en, arst_n, fsm_output
);
  input clk;
  input en;
  input arst_n;
  output [1:0] fsm_output;
  reg [1:0] fsm_output;


  // FSM State Type Declaration for edge_counter_core_fsm_1
  parameter
    st_core_rlp = 1'd0,
    st_main = 1'd1,
    state_x = 1'b0;

  reg [0:0] state_var;
  reg [0:0] state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : edge_counter_core_fsm_1
    case (state_var)
      st_core_rlp : begin
        fsm_output = 2'b1;
        state_var_NS = st_main;
      end
      st_main : begin
        fsm_output = 2'b10;
        state_var_NS = st_main;
      end
      default : begin
        fsm_output = 2'b00;
        state_var_NS = st_core_rlp;
      end
    endcase
  end

  always @(posedge clk or negedge arst_n) begin
    if ( ~ arst_n ) begin
      state_var <= st_core_rlp;
    end
    else if ( en ) begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    edge_counter_core
// ------------------------------------------------------------------


module edge_counter_core (
  clk, en, arst_n, vin_rsc_mgc_in_wire_en_ld, vin_rsc_mgc_in_wire_en_d, vout_rsc_mgc_inout_stdreg_en_ldout,
      vout_rsc_mgc_inout_stdreg_en_dout, sum_rsc_mgc_out_stdreg_d
);
  input clk;
  input en;
  input arst_n;
  output vin_rsc_mgc_in_wire_en_ld;
  reg vin_rsc_mgc_in_wire_en_ld;
  input [89:0] vin_rsc_mgc_in_wire_en_d;
  output vout_rsc_mgc_inout_stdreg_en_ldout;
  reg vout_rsc_mgc_inout_stdreg_en_ldout;
  output [29:0] vout_rsc_mgc_inout_stdreg_en_dout;
  output [29:0] sum_rsc_mgc_out_stdreg_d;
  reg [29:0] sum_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations
  wire [1:0] fsm_output;
  wire [13:0] FRAME_acc_13_tmp;
  wire [15:0] nl_FRAME_acc_13_tmp;
  reg [89:0] regs_regs_0_sva;
  reg exit_FRAME_sva;
  reg [18:0] FRAME_p_1_sva_1;
  reg [9:0] regs_regs_slc_regs_regs_2_2_itm;
  reg [9:0] regs_regs_slc_regs_regs_2_3_itm;
  reg [9:0] regs_regs_slc_regs_regs_2_1_itm;
  reg [9:0] regs_regs_slc_regs_regs_2_5_itm;
  reg [9:0] regs_regs_slc_regs_regs_2_itm;
  reg [9:0] regs_regs_slc_regs_regs_2_4_itm;
  reg [9:0] getPixel_slc_regs_regs_2_itm;
  reg [9:0] getPixel_slc_regs_regs_2_1_itm;
  reg [9:0] getPixel_slc_regs_regs_2_2_itm;
  reg slc_gx_2_itm_1;
  reg slc_gx_itm_1;
  reg [6:0] FRAME_slc_21_itm_1;
  reg FRAME_nand_itm_1;
  reg FRAME_slc_getPixel_acc_11_psp_17_itm_1;
  reg slc_gy_2_itm_1;
  reg slc_gy_itm_1;
  reg [6:0] FRAME_slc_39_itm_1;
  reg FRAME_nand_1_itm_1;
  reg FRAME_slc_getPixel_acc_psp_17_itm_1;
  reg FRAME_slc_1_itm_1;
  reg FRAME_p_slc_FRAME_p_2_itm_1;
  reg [29:0] FRAME_and_itm_1;
  reg exit_FRAME_sva_1_st_1;
  reg main_stage_0_2;
  reg [8:0] FRAME_slc_24_itm_2;
  reg [8:0] FRAME_slc_42_itm_2;
  wire [14:0] FRAME_acc_7_psp_sva;
  wire [15:0] nl_FRAME_acc_7_psp_sva;
  wire [18:0] FRAME_p_1_sva_1_mx0w0;
  wire [19:0] nl_FRAME_p_1_sva_1_mx0w0;
  reg reg_slc_getPixel_acc_psp_33_itm_1_cse;
  reg reg_slc_getPixel_acc_psp_30_itm_1_cse;
  reg reg_slc_gy_4_itm_1_cse;
  reg reg_slc_getPixel_acc_psp_17_itm_1_cse;
  reg reg_slc_getPixel_acc_psp_22_itm_1_cse;
  reg reg_slc_getPixel_acc_11_psp_33_itm_1_cse;
  reg reg_slc_getPixel_acc_11_psp_30_itm_1_cse;
  reg reg_slc_gx_4_itm_1_cse;
  reg reg_slc_getPixel_acc_11_psp_17_itm_1_cse;
  reg reg_slc_getPixel_acc_11_psp_22_itm_1_cse;
  reg reg_vout_rsc_mgc_inout_stdreg_en_dout_tmp_1;
  reg reg_vout_rsc_mgc_inout_stdreg_en_dout_tmp_2;
  reg [9:0] reg_vout_rsc_mgc_inout_stdreg_en_dout_tmp_3;
  wire [13:0] res_1_lpi_1_dfm_1_mx0;
  reg [1:0] reg_vout_rsc_mgc_inout_stdreg_en_dout_reg;
  wire [29:0] tmp_sum_1_sva_1;
  wire [30:0] nl_tmp_sum_1_sva_1;
  wire [89:0] regs_regs_1_sva_mx0;
  wire [13:0] FRAME_acc_14_psp_sva;
  wire [15:0] nl_FRAME_acc_14_psp_sva;
  wire [18:0] FRAME_p_1_lpi_1_dfm;
  wire [14:0] getPixel_acc_33_sdt;
  wire [15:0] nl_getPixel_acc_33_sdt;
  wire [11:0] getPixel_acc_psp;
  wire [12:0] nl_getPixel_acc_psp;
  wire [2:0] acc_imod_4_sva;
  wire [3:0] nl_acc_imod_4_sva;
  wire [14:0] getPixel_acc_24_sdt;
  wire [15:0] nl_getPixel_acc_24_sdt;
  wire [11:0] getPixel_acc_42_psp;
  wire [12:0] nl_getPixel_acc_42_psp;
  wire [2:0] acc_imod_1_sva;
  wire [3:0] nl_acc_imod_1_sva;
  wire [12:0] getPixel_acc_29_sdt;
  wire [13:0] nl_getPixel_acc_29_sdt;
  wire [12:0] getPixel_acc_28_sdt;
  wire [13:0] nl_getPixel_acc_28_sdt;
  wire [11:0] getPixel_acc_cse_5_sva;
  wire [12:0] nl_getPixel_acc_cse_5_sva;
  wire [11:0] getPixel_acc_cse_sva;
  wire [12:0] nl_getPixel_acc_cse_sva;
  wire [11:0] getPixel_acc_cse_3_sva;
  wire [12:0] nl_getPixel_acc_cse_3_sva;
  wire [12:0] getPixel_acc_20_sdt;
  wire [13:0] nl_getPixel_acc_20_sdt;
  wire [12:0] getPixel_acc_19_sdt;
  wire [13:0] nl_getPixel_acc_19_sdt;
  wire [14:0] FRAME_acc_itm;
  wire [15:0] nl_FRAME_acc_itm;
  wire [2:0] FRAME_acc_46_itm;
  wire [3:0] nl_FRAME_acc_46_itm;
  wire [5:0] FRAME_acc_43_itm;
  wire [6:0] nl_FRAME_acc_43_itm;
  wire [2:0] FRAME_acc_24_itm;
  wire [3:0] nl_FRAME_acc_24_itm;
  wire [5:0] FRAME_acc_21_itm;
  wire [6:0] nl_FRAME_acc_21_itm;
  wire [11:0] ACC1_3_ACC1_1_1_getPixel_acc_itm;
  wire [12:0] nl_ACC1_3_ACC1_1_1_getPixel_acc_itm;

  wire[13:0] FRAME_mux_2_nl;
  wire[12:0] mux_8_nl;

  // Interconnect Declarations for Component Instantiations 
  edge_counter_core_fsm edge_counter_core_fsm_inst (
      .clk(clk),
      .en(en),
      .arst_n(arst_n),
      .fsm_output(fsm_output)
    );
  assign vout_rsc_mgc_inout_stdreg_en_dout = {({{16{reg_vout_rsc_mgc_inout_stdreg_en_dout_reg[1]}},
      reg_vout_rsc_mgc_inout_stdreg_en_dout_reg}) , reg_vout_rsc_mgc_inout_stdreg_en_dout_tmp_1
      , reg_vout_rsc_mgc_inout_stdreg_en_dout_tmp_2 , reg_vout_rsc_mgc_inout_stdreg_en_dout_tmp_3};
  assign nl_FRAME_acc_itm = conv_u2s_14_15(FRAME_p_1_sva_1_mx0w0[18:5]) + 15'b100110010111011;
  assign FRAME_acc_itm = nl_FRAME_acc_itm[14:0];
  assign nl_tmp_sum_1_sva_1 = conv_s2s_15_30(FRAME_acc_7_psp_sva) + FRAME_and_itm_1;
  assign tmp_sum_1_sva_1 = nl_tmp_sum_1_sva_1[29:0];
  assign nl_FRAME_p_1_sva_1_mx0w0 = FRAME_p_1_lpi_1_dfm + 19'b1;
  assign FRAME_p_1_sva_1_mx0w0 = nl_FRAME_p_1_sva_1_mx0w0[18:0];
  assign regs_regs_1_sva_mx0 = regs_regs_0_sva & (signext_90_1(fsm_output[1]));
  assign nl_FRAME_acc_14_psp_sva = (conv_s2s_13_14(conv_u2s_12_13({reg_slc_getPixel_acc_11_psp_33_itm_1_cse
      , 1'b0 , reg_slc_getPixel_acc_11_psp_33_itm_1_cse , 1'b0 , reg_slc_getPixel_acc_11_psp_33_itm_1_cse
      , 1'b0 , reg_slc_getPixel_acc_11_psp_33_itm_1_cse , 1'b0 , reg_slc_getPixel_acc_11_psp_33_itm_1_cse
      , 1'b0 , ({{1{reg_slc_gx_4_itm_1_cse}}, reg_slc_gx_4_itm_1_cse})}) + conv_s2s_11_13(conv_u2s_10_11({reg_slc_getPixel_acc_11_psp_30_itm_1_cse
      , 1'b0 , reg_slc_getPixel_acc_11_psp_30_itm_1_cse , 1'b0 , reg_slc_getPixel_acc_11_psp_30_itm_1_cse
      , 1'b0 , reg_slc_getPixel_acc_11_psp_30_itm_1_cse , 1'b0 , ({{1{slc_gx_2_itm_1}},
      slc_gx_2_itm_1})}) + conv_s2s_9_11(readslicef_10_9_1((conv_u2s_9_10({reg_slc_gx_4_itm_1_cse
      , 1'b0 , reg_slc_gx_4_itm_1_cse , 1'b0 , reg_slc_gx_4_itm_1_cse , 1'b0 , ({{1{slc_gx_itm_1}},
      slc_gx_itm_1}) , 1'b1}) + conv_s2s_8_10({FRAME_slc_21_itm_1 , FRAME_nand_itm_1}))))))
      + conv_u2s_11_14({reg_slc_getPixel_acc_11_psp_17_itm_1_cse , (conv_u2u_9_10({reg_slc_getPixel_acc_11_psp_17_itm_1_cse
      , 1'b0 , reg_slc_getPixel_acc_11_psp_17_itm_1_cse , 1'b0 , reg_slc_getPixel_acc_11_psp_17_itm_1_cse
      , 1'b0 , reg_slc_getPixel_acc_11_psp_17_itm_1_cse , 1'b0 , reg_slc_getPixel_acc_11_psp_17_itm_1_cse})
      + conv_u2u_9_10(FRAME_slc_24_itm_2))})) + ({reg_slc_getPixel_acc_11_psp_22_itm_1_cse
      , 1'b0 , reg_slc_getPixel_acc_11_psp_22_itm_1_cse , 1'b0 , reg_slc_getPixel_acc_11_psp_22_itm_1_cse
      , 1'b0 , reg_slc_getPixel_acc_11_psp_22_itm_1_cse , 1'b0 , reg_slc_getPixel_acc_11_psp_22_itm_1_cse
      , 1'b0 , reg_slc_getPixel_acc_11_psp_22_itm_1_cse , 1'b0 , reg_slc_getPixel_acc_11_psp_22_itm_1_cse
      , FRAME_slc_getPixel_acc_11_psp_17_itm_1});
  assign FRAME_acc_14_psp_sva = nl_FRAME_acc_14_psp_sva[13:0];
  assign nl_FRAME_acc_13_tmp = (conv_s2s_13_14(conv_u2s_12_13({reg_slc_getPixel_acc_psp_33_itm_1_cse
      , 1'b0 , reg_slc_getPixel_acc_psp_33_itm_1_cse , 1'b0 , reg_slc_getPixel_acc_psp_33_itm_1_cse
      , 1'b0 , reg_slc_getPixel_acc_psp_33_itm_1_cse , 1'b0 , reg_slc_getPixel_acc_psp_33_itm_1_cse
      , 1'b0 , ({{1{reg_slc_gy_4_itm_1_cse}}, reg_slc_gy_4_itm_1_cse})}) + conv_s2s_11_13(conv_u2s_10_11({reg_slc_getPixel_acc_psp_30_itm_1_cse
      , 1'b0 , reg_slc_getPixel_acc_psp_30_itm_1_cse , 1'b0 , reg_slc_getPixel_acc_psp_30_itm_1_cse
      , 1'b0 , reg_slc_getPixel_acc_psp_30_itm_1_cse , 1'b0 , ({{1{slc_gy_2_itm_1}},
      slc_gy_2_itm_1})}) + conv_s2s_9_11(readslicef_10_9_1((conv_u2s_9_10({reg_slc_gy_4_itm_1_cse
      , 1'b0 , reg_slc_gy_4_itm_1_cse , 1'b0 , reg_slc_gy_4_itm_1_cse , 1'b0 , ({{1{slc_gy_itm_1}},
      slc_gy_itm_1}) , 1'b1}) + conv_s2s_8_10({FRAME_slc_39_itm_1 , FRAME_nand_1_itm_1}))))))
      + conv_u2s_11_14({reg_slc_getPixel_acc_psp_17_itm_1_cse , (conv_u2u_9_10({reg_slc_getPixel_acc_psp_17_itm_1_cse
      , 1'b0 , reg_slc_getPixel_acc_psp_17_itm_1_cse , 1'b0 , reg_slc_getPixel_acc_psp_17_itm_1_cse
      , 1'b0 , reg_slc_getPixel_acc_psp_17_itm_1_cse , 1'b0 , reg_slc_getPixel_acc_psp_17_itm_1_cse})
      + conv_u2u_9_10(FRAME_slc_42_itm_2))})) + ({reg_slc_getPixel_acc_psp_22_itm_1_cse
      , 1'b0 , reg_slc_getPixel_acc_psp_22_itm_1_cse , 1'b0 , reg_slc_getPixel_acc_psp_22_itm_1_cse
      , 1'b0 , reg_slc_getPixel_acc_psp_22_itm_1_cse , 1'b0 , reg_slc_getPixel_acc_psp_22_itm_1_cse
      , 1'b0 , reg_slc_getPixel_acc_psp_22_itm_1_cse , 1'b0 , reg_slc_getPixel_acc_psp_22_itm_1_cse
      , FRAME_slc_getPixel_acc_psp_17_itm_1});
  assign FRAME_acc_13_tmp = nl_FRAME_acc_13_tmp[13:0];
  assign FRAME_mux_2_nl = MUX_v_14_2_2({FRAME_acc_14_psp_sva , ({1'b0 , ((~ (FRAME_acc_14_psp_sva[12:0]))
      + 13'b1)})}, FRAME_acc_14_psp_sva[13]);
  assign mux_8_nl = MUX_v_13_2_2({(FRAME_acc_13_tmp[12:0]) , ((~ (FRAME_acc_13_tmp[12:0]))
      + 13'b1)}, FRAME_acc_13_tmp[13]);
  assign nl_FRAME_acc_7_psp_sva = conv_s2s_14_15(FRAME_mux_2_nl) + conv_u2s_13_15(mux_8_nl);
  assign FRAME_acc_7_psp_sva = nl_FRAME_acc_7_psp_sva[14:0];
  assign res_1_lpi_1_dfm_1_mx0 = MUX_v_14_2_2({14'b1111111111 , (FRAME_acc_7_psp_sva[13:0])},
      readslicef_15_1_14((FRAME_acc_7_psp_sva + 15'b111110000000001)));
  assign FRAME_p_1_lpi_1_dfm = FRAME_p_1_sva_1 & (signext_19_1(~ exit_FRAME_sva));
  assign nl_getPixel_acc_33_sdt = conv_u2u_14_15({(conv_u2u_12_13(conv_u2u_11_12(conv_u2u_10_11(vin_rsc_mgc_in_wire_en_d[59:50])
      + conv_u2u_10_11(~ getPixel_slc_regs_regs_2_itm)) + conv_u2u_11_12(conv_u2u_10_11(~
      getPixel_slc_regs_regs_2_1_itm) + conv_u2u_10_11(~ getPixel_slc_regs_regs_2_2_itm)))
      + conv_u2u_12_13(getPixel_acc_29_sdt[12:1])) , (getPixel_acc_29_sdt[0])}) +
      conv_u2u_14_15({(conv_u2u_11_13(conv_u2u_10_11(vin_rsc_mgc_in_wire_en_d[39:30])
      + conv_u2u_10_11(vin_rsc_mgc_in_wire_en_d[49:40])) + conv_u2u_12_13(getPixel_acc_28_sdt[12:1]))
      , (getPixel_acc_28_sdt[0])});
  assign getPixel_acc_33_sdt = nl_getPixel_acc_33_sdt[14:0];
  assign nl_getPixel_acc_psp = (getPixel_acc_33_sdt[14:3]) + 12'b100100000001;
  assign getPixel_acc_psp = nl_getPixel_acc_psp[11:0];
  assign nl_acc_imod_4_sva = (readslicef_4_3_1((conv_u2u_3_4({(readslicef_3_2_1((conv_u2u_2_3({(FRAME_acc_43_itm[3])
      , 1'b1}) + conv_u2u_2_3({(~ (FRAME_acc_43_itm[4])) , 1'b1})))) , 1'b1}) + conv_u2u_2_4({(~
      (FRAME_acc_43_itm[2])) , (~ (FRAME_acc_43_itm[5]))})))) + ({2'b10 , (FRAME_acc_43_itm[1])});
  assign acc_imod_4_sva = nl_acc_imod_4_sva[2:0];
  assign nl_FRAME_acc_46_itm = ({1'b1 , (acc_imod_4_sva[0]) , 1'b1}) + conv_u2s_2_3({(~
      (acc_imod_4_sva[1])) , (~ (acc_imod_4_sva[2]))});
  assign FRAME_acc_46_itm = nl_FRAME_acc_46_itm[2:0];
  assign nl_FRAME_acc_43_itm = conv_s2s_5_6({(readslicef_5_4_1((({3'b101 , (getPixel_acc_33_sdt[0])
      , 1'b1}) + conv_u2s_4_5({(readslicef_4_3_1((conv_u2u_3_4({(readslicef_3_2_1((conv_u2u_2_3({(~
      (getPixel_acc_33_sdt[1])) , 1'b1}) + conv_u2u_2_3({(getPixel_acc_33_sdt[2])
      , (getPixel_acc_psp[5])})))) , 1'b1}) + conv_u2u_3_4({(readslicef_3_2_1((conv_u2u_2_3({(~
      (getPixel_acc_psp[0])) , 1'b1}) + conv_u2u_2_3({(getPixel_acc_psp[1]) , (~
      (getPixel_acc_psp[4]))})))) , (getPixel_acc_psp[7])})))) , (~ (getPixel_acc_psp[8]))}))))
      , 1'b1}) + conv_s2s_5_6({(readslicef_5_4_1((conv_u2s_3_5({(readslicef_3_2_1((conv_u2u_2_3({(~
      (getPixel_acc_psp[2])) , 1'b1}) + conv_u2u_2_3({(getPixel_acc_psp[3]) , 1'b1}))))
      , 1'b1}) + conv_s2s_3_5({(~ (getPixel_acc_psp[11:10])) , (~ (getPixel_acc_psp[6]))}))))
      , (getPixel_acc_psp[9])});
  assign FRAME_acc_43_itm = nl_FRAME_acc_43_itm[5:0];
  assign nl_getPixel_acc_24_sdt = conv_u2u_14_15({(conv_u2u_12_13(conv_u2u_11_12(conv_u2u_10_11(~
      (regs_regs_0_sva[29:20])) + conv_u2u_10_11(regs_regs_0_sva[69:60])) + conv_u2u_11_12(conv_u2u_10_11(regs_regs_0_sva[79:70])
      + conv_u2u_10_11(regs_regs_0_sva[89:80]))) + conv_u2u_12_13(getPixel_acc_20_sdt[12:1]))
      , (getPixel_acc_20_sdt[0])}) + conv_u2u_14_15({(conv_u2u_11_13(conv_u2u_10_11(~
      (regs_regs_0_sva[9:0])) + conv_u2u_10_11(~ (regs_regs_0_sva[19:10]))) + conv_u2u_12_13(getPixel_acc_19_sdt[12:1]))
      , (getPixel_acc_19_sdt[0])});
  assign getPixel_acc_24_sdt = nl_getPixel_acc_24_sdt[14:0];
  assign nl_getPixel_acc_42_psp = (getPixel_acc_24_sdt[14:3]) + 12'b100100000001;
  assign getPixel_acc_42_psp = nl_getPixel_acc_42_psp[11:0];
  assign nl_acc_imod_1_sva = (readslicef_4_3_1((conv_u2u_3_4({(readslicef_3_2_1((conv_u2u_2_3({(FRAME_acc_21_itm[3])
      , 1'b1}) + conv_u2u_2_3({(~ (FRAME_acc_21_itm[4])) , 1'b1})))) , 1'b1}) + conv_u2u_2_4({(~
      (FRAME_acc_21_itm[2])) , (~ (FRAME_acc_21_itm[5]))})))) + ({2'b10 , (FRAME_acc_21_itm[1])});
  assign acc_imod_1_sva = nl_acc_imod_1_sva[2:0];
  assign nl_FRAME_acc_24_itm = ({1'b1 , (acc_imod_1_sva[0]) , 1'b1}) + conv_u2s_2_3({(~
      (acc_imod_1_sva[1])) , (~ (acc_imod_1_sva[2]))});
  assign FRAME_acc_24_itm = nl_FRAME_acc_24_itm[2:0];
  assign nl_FRAME_acc_21_itm = conv_s2s_5_6({(readslicef_5_4_1((({3'b101 , (getPixel_acc_24_sdt[0])
      , 1'b1}) + conv_u2s_4_5({(readslicef_4_3_1((conv_u2u_3_4({(readslicef_3_2_1((conv_u2u_2_3({(~
      (getPixel_acc_24_sdt[1])) , 1'b1}) + conv_u2u_2_3({(getPixel_acc_24_sdt[2])
      , (getPixel_acc_42_psp[5])})))) , 1'b1}) + conv_u2u_3_4({(readslicef_3_2_1((conv_u2u_2_3({(~
      (getPixel_acc_42_psp[0])) , 1'b1}) + conv_u2u_2_3({(getPixel_acc_42_psp[1])
      , (~ (getPixel_acc_42_psp[4]))})))) , (getPixel_acc_42_psp[7])})))) , (~ (getPixel_acc_42_psp[8]))}))))
      , 1'b1}) + conv_s2s_5_6({(readslicef_5_4_1((conv_u2s_3_5({(readslicef_3_2_1((conv_u2u_2_3({(~
      (getPixel_acc_42_psp[2])) , 1'b1}) + conv_u2u_2_3({(getPixel_acc_42_psp[3])
      , 1'b1})))) , 1'b1}) + conv_s2s_3_5({(~ (getPixel_acc_42_psp[11:10])) , (~
      (getPixel_acc_42_psp[6]))})))) , (getPixel_acc_42_psp[9])});
  assign FRAME_acc_21_itm = nl_FRAME_acc_21_itm[5:0];
  assign nl_getPixel_acc_29_sdt = conv_u2u_12_13(~ getPixel_acc_cse_sva) + conv_u2u_12_13(getPixel_acc_cse_3_sva);
  assign getPixel_acc_29_sdt = nl_getPixel_acc_29_sdt[12:0];
  assign nl_getPixel_acc_28_sdt = conv_u2u_12_13(~ ACC1_3_ACC1_1_1_getPixel_acc_itm)
      + conv_u2u_12_13(getPixel_acc_cse_5_sva);
  assign getPixel_acc_28_sdt = nl_getPixel_acc_28_sdt[12:0];
  assign nl_getPixel_acc_cse_5_sva = conv_u2u_11_12(conv_u2u_10_11(vin_rsc_mgc_in_wire_en_d[19:10])
      + conv_u2u_10_11(vin_rsc_mgc_in_wire_en_d[9:0])) + conv_u2u_10_12(vin_rsc_mgc_in_wire_en_d[29:20]);
  assign getPixel_acc_cse_5_sva = nl_getPixel_acc_cse_5_sva[11:0];
  assign nl_getPixel_acc_cse_sva = conv_u2u_11_12(conv_u2u_10_11(regs_regs_slc_regs_regs_2_5_itm)
      + conv_u2u_10_11(regs_regs_slc_regs_regs_2_itm)) + conv_u2u_10_12(regs_regs_slc_regs_regs_2_4_itm);
  assign getPixel_acc_cse_sva = nl_getPixel_acc_cse_sva[11:0];
  assign nl_getPixel_acc_cse_3_sva = conv_u2u_11_12(conv_u2u_10_11(vin_rsc_mgc_in_wire_en_d[79:70])
      + conv_u2u_10_11(vin_rsc_mgc_in_wire_en_d[69:60])) + conv_u2u_10_12(vin_rsc_mgc_in_wire_en_d[89:80]);
  assign getPixel_acc_cse_3_sva = nl_getPixel_acc_cse_3_sva[11:0];
  assign nl_getPixel_acc_20_sdt = conv_u2u_12_13(getPixel_acc_cse_3_sva) + conv_u2u_12_13(getPixel_acc_cse_sva);
  assign getPixel_acc_20_sdt = nl_getPixel_acc_20_sdt[12:0];
  assign nl_getPixel_acc_19_sdt = conv_u2u_12_13(~ ACC1_3_ACC1_1_1_getPixel_acc_itm)
      + conv_u2u_12_13(~ getPixel_acc_cse_5_sva);
  assign getPixel_acc_19_sdt = nl_getPixel_acc_19_sdt[12:0];
  assign nl_ACC1_3_ACC1_1_1_getPixel_acc_itm = conv_u2u_11_12(conv_u2u_10_11(regs_regs_slc_regs_regs_2_2_itm)
      + conv_u2u_10_11(regs_regs_slc_regs_regs_2_3_itm)) + conv_u2u_10_12(regs_regs_slc_regs_regs_2_1_itm);
  assign ACC1_3_ACC1_1_1_getPixel_acc_itm = nl_ACC1_3_ACC1_1_1_getPixel_acc_itm[11:0];
  always @(posedge clk or negedge arst_n) begin
    if ( ~ arst_n ) begin
      sum_rsc_mgc_out_stdreg_d <= 30'b0;
      reg_vout_rsc_mgc_inout_stdreg_en_dout_reg <= 2'b0;
      vout_rsc_mgc_inout_stdreg_en_ldout <= 1'b0;
      vin_rsc_mgc_in_wire_en_ld <= 1'b0;
      exit_FRAME_sva_1_st_1 <= 1'b0;
      FRAME_and_itm_1 <= 30'b0;
      FRAME_slc_1_itm_1 <= 1'b0;
      FRAME_p_slc_FRAME_p_2_itm_1 <= 1'b0;
      reg_slc_getPixel_acc_psp_33_itm_1_cse <= 1'b0;
      reg_slc_gy_4_itm_1_cse <= 1'b0;
      reg_slc_getPixel_acc_psp_30_itm_1_cse <= 1'b0;
      slc_gy_2_itm_1 <= 1'b0;
      slc_gy_itm_1 <= 1'b0;
      FRAME_slc_39_itm_1 <= 7'b0;
      FRAME_nand_1_itm_1 <= 1'b0;
      reg_slc_getPixel_acc_psp_17_itm_1_cse <= 1'b0;
      FRAME_slc_42_itm_2 <= 9'b0;
      reg_slc_getPixel_acc_psp_22_itm_1_cse <= 1'b0;
      FRAME_slc_getPixel_acc_psp_17_itm_1 <= 1'b0;
      reg_slc_getPixel_acc_11_psp_33_itm_1_cse <= 1'b0;
      reg_slc_gx_4_itm_1_cse <= 1'b0;
      reg_slc_getPixel_acc_11_psp_30_itm_1_cse <= 1'b0;
      slc_gx_2_itm_1 <= 1'b0;
      slc_gx_itm_1 <= 1'b0;
      FRAME_slc_21_itm_1 <= 7'b0;
      FRAME_nand_itm_1 <= 1'b0;
      reg_slc_getPixel_acc_11_psp_17_itm_1_cse <= 1'b0;
      FRAME_slc_24_itm_2 <= 9'b0;
      reg_slc_getPixel_acc_11_psp_22_itm_1_cse <= 1'b0;
      FRAME_slc_getPixel_acc_11_psp_17_itm_1 <= 1'b0;
      main_stage_0_2 <= 1'b0;
      FRAME_p_1_sva_1 <= 19'b0;
      exit_FRAME_sva <= 1'b1;
      getPixel_slc_regs_regs_2_itm <= 10'b0;
      getPixel_slc_regs_regs_2_1_itm <= 10'b0;
      getPixel_slc_regs_regs_2_2_itm <= 10'b0;
      regs_regs_0_sva <= 90'b0;
      regs_regs_slc_regs_regs_2_5_itm <= 10'b0;
      regs_regs_slc_regs_regs_2_itm <= 10'b0;
      regs_regs_slc_regs_regs_2_4_itm <= 10'b0;
      regs_regs_slc_regs_regs_2_2_itm <= 10'b0;
      regs_regs_slc_regs_regs_2_3_itm <= 10'b0;
      regs_regs_slc_regs_regs_2_1_itm <= 10'b0;
      reg_vout_rsc_mgc_inout_stdreg_en_dout_tmp_1 <= 1'b0;
      reg_vout_rsc_mgc_inout_stdreg_en_dout_tmp_2 <= 1'b0;
      reg_vout_rsc_mgc_inout_stdreg_en_dout_tmp_3 <= 10'b0;
    end
    else begin
      if ( en ) begin
        sum_rsc_mgc_out_stdreg_d <= MUX_v_30_2_2({tmp_sum_1_sva_1 , sum_rsc_mgc_out_stdreg_d},
            ~(main_stage_0_2 & (fsm_output[1]) & exit_FRAME_sva_1_st_1));
        reg_vout_rsc_mgc_inout_stdreg_en_dout_reg <= res_1_lpi_1_dfm_1_mx0[13:12];
        vout_rsc_mgc_inout_stdreg_en_ldout <= main_stage_0_2 & (fsm_output[1]);
        vin_rsc_mgc_in_wire_en_ld <= 1'b1;
        exit_FRAME_sva_1_st_1 <= ~ (FRAME_acc_itm[14]);
        FRAME_and_itm_1 <= tmp_sum_1_sva_1 & ({{29{main_stage_0_2}}, main_stage_0_2})
            & (signext_30_1(~ exit_FRAME_sva));
        FRAME_slc_1_itm_1 <= readslicef_19_1_18(((~ FRAME_p_1_lpi_1_dfm) + 19'b110011010001010001));
        FRAME_p_slc_FRAME_p_2_itm_1 <= FRAME_p_1_lpi_1_dfm[0];
        reg_slc_getPixel_acc_psp_33_itm_1_cse <= getPixel_acc_psp[10];
        reg_slc_gy_4_itm_1_cse <= getPixel_acc_psp[6];
        reg_slc_getPixel_acc_psp_30_itm_1_cse <= getPixel_acc_psp[8];
        slc_gy_2_itm_1 <= getPixel_acc_psp[4];
        slc_gy_itm_1 <= getPixel_acc_psp[2];
        FRAME_slc_39_itm_1 <= readslicef_8_7_1((conv_s2s_6_8({(~ (getPixel_acc_psp[3]))
            , (readslicef_5_4_1((conv_u2u_4_5({(getPixel_acc_psp[3]) , 1'b0 , (getPixel_acc_psp[3])
            , 1'b1}) + conv_u2u_4_5({2'b11 , (getPixel_acc_psp[1]) , (FRAME_acc_43_itm[4])}))))
            , 1'b1}) + conv_u2s_6_8({(readslicef_6_5_1((conv_u2u_5_6({(readslicef_5_4_1((conv_u2u_4_5({(readslicef_4_3_1((conv_u2u_3_4({(getPixel_acc_psp[0])
            , (getPixel_acc_33_sdt[1]) , 1'b1}) + conv_u2u_3_4({(FRAME_acc_43_itm[4])
            , (getPixel_acc_psp[0]) , 1'b1})))) , 1'b1}) + conv_u2u_4_5({(~ (FRAME_acc_43_itm[5]))
            , 1'b1 , (~ (FRAME_acc_43_itm[5])) , (FRAME_acc_43_itm[2])})))) , 1'b1})
            + conv_u2u_5_6({(getPixel_acc_psp[4]) , (getPixel_acc_psp[1]) , (signext_2_1(getPixel_acc_psp[10]))
            , (FRAME_acc_43_itm[3])})))) , (acc_imod_4_sva[1])})));
        FRAME_nand_1_itm_1 <= ~((FRAME_acc_46_itm[2]) & (~ (getPixel_acc_psp[11])));
        reg_slc_getPixel_acc_psp_17_itm_1_cse <= getPixel_acc_psp[9];
        FRAME_slc_42_itm_2 <= readslicef_10_9_1((({(getPixel_acc_psp[7]) , 1'b0 ,
            (getPixel_acc_psp[7]) , 1'b0 , (getPixel_acc_psp[7]) , 1'b0 , (getPixel_acc_psp[7])
            , 1'b0 , (getPixel_acc_psp[7]) , 1'b1}) + conv_u2u_9_10({(readslicef_9_8_1((conv_u2u_8_9({(getPixel_acc_psp[5])
            , 1'b0 , (getPixel_acc_psp[5]) , 1'b0 , (getPixel_acc_psp[5]) , 1'b0
            , (getPixel_acc_psp[5]) , 1'b1}) + conv_u2u_7_9({(getPixel_acc_psp[4])
            , 1'b0 , (getPixel_acc_psp[2]) , 1'b0 , (signext_2_1(getPixel_acc_psp[8]))
            , (~ (acc_imod_4_sva[2]))})))) , ((getPixel_acc_psp[11]) & (~ (FRAME_acc_46_itm[2]))
            & (FRAME_acc_46_itm[1]))})));
        reg_slc_getPixel_acc_psp_22_itm_1_cse <= getPixel_acc_psp[11];
        FRAME_slc_getPixel_acc_psp_17_itm_1 <= getPixel_acc_33_sdt[2];
        reg_slc_getPixel_acc_11_psp_33_itm_1_cse <= getPixel_acc_42_psp[10];
        reg_slc_gx_4_itm_1_cse <= getPixel_acc_42_psp[6];
        reg_slc_getPixel_acc_11_psp_30_itm_1_cse <= getPixel_acc_42_psp[8];
        slc_gx_2_itm_1 <= getPixel_acc_42_psp[4];
        slc_gx_itm_1 <= getPixel_acc_42_psp[2];
        FRAME_slc_21_itm_1 <= readslicef_8_7_1((conv_s2s_6_8({(~ (getPixel_acc_42_psp[3]))
            , (readslicef_5_4_1((conv_u2u_4_5({(getPixel_acc_42_psp[3]) , 1'b0 ,
            (getPixel_acc_42_psp[3]) , 1'b1}) + conv_u2u_4_5({2'b11 , (getPixel_acc_42_psp[1])
            , (FRAME_acc_21_itm[4])})))) , 1'b1}) + conv_u2s_6_8({(readslicef_6_5_1((conv_u2u_5_6({(readslicef_5_4_1((conv_u2u_4_5({(readslicef_4_3_1((conv_u2u_3_4({(getPixel_acc_42_psp[0])
            , (getPixel_acc_24_sdt[1]) , 1'b1}) + conv_u2u_3_4({(FRAME_acc_21_itm[4])
            , (getPixel_acc_42_psp[0]) , 1'b1})))) , 1'b1}) + conv_u2u_4_5({(~ (FRAME_acc_21_itm[5]))
            , 1'b1 , (~ (FRAME_acc_21_itm[5])) , (FRAME_acc_21_itm[2])})))) , 1'b1})
            + conv_u2u_5_6({(getPixel_acc_42_psp[4]) , (getPixel_acc_42_psp[1]) ,
            (signext_2_1(getPixel_acc_42_psp[10])) , (FRAME_acc_21_itm[3])})))) ,
            (acc_imod_1_sva[1])})));
        FRAME_nand_itm_1 <= ~((FRAME_acc_24_itm[2]) & (~ (getPixel_acc_42_psp[11])));
        reg_slc_getPixel_acc_11_psp_17_itm_1_cse <= getPixel_acc_42_psp[9];
        FRAME_slc_24_itm_2 <= readslicef_10_9_1((({(getPixel_acc_42_psp[7]) , 1'b0
            , (getPixel_acc_42_psp[7]) , 1'b0 , (getPixel_acc_42_psp[7]) , 1'b0 ,
            (getPixel_acc_42_psp[7]) , 1'b0 , (getPixel_acc_42_psp[7]) , 1'b1}) +
            conv_u2u_9_10({(readslicef_9_8_1((conv_u2u_8_9({(getPixel_acc_42_psp[5])
            , 1'b0 , (getPixel_acc_42_psp[5]) , 1'b0 , (getPixel_acc_42_psp[5]) ,
            1'b0 , (getPixel_acc_42_psp[5]) , 1'b1}) + conv_u2u_7_9({(getPixel_acc_42_psp[4])
            , 1'b0 , (getPixel_acc_42_psp[2]) , 1'b0 , (signext_2_1(getPixel_acc_42_psp[8]))
            , (~ (acc_imod_1_sva[2]))})))) , ((getPixel_acc_42_psp[11]) & (~ (FRAME_acc_24_itm[2]))
            & (FRAME_acc_24_itm[1]))})));
        reg_slc_getPixel_acc_11_psp_22_itm_1_cse <= getPixel_acc_42_psp[11];
        FRAME_slc_getPixel_acc_11_psp_17_itm_1 <= getPixel_acc_24_sdt[2];
        main_stage_0_2 <= fsm_output[1];
        FRAME_p_1_sva_1 <= MUX_v_19_2_2({FRAME_p_1_sva_1 , FRAME_p_1_sva_1_mx0w0},
            fsm_output[1]);
        exit_FRAME_sva <= MUX_s_1_2_2({exit_FRAME_sva , (~ (FRAME_acc_itm[14]))},
            fsm_output[1]);
        getPixel_slc_regs_regs_2_itm <= regs_regs_1_sva_mx0[39:30];
        getPixel_slc_regs_regs_2_1_itm <= regs_regs_1_sva_mx0[49:40];
        getPixel_slc_regs_regs_2_2_itm <= regs_regs_1_sva_mx0[59:50];
        regs_regs_0_sva <= MUX_v_90_2_2({regs_regs_0_sva , vin_rsc_mgc_in_wire_en_d},
            fsm_output[1]);
        regs_regs_slc_regs_regs_2_5_itm <= regs_regs_1_sva_mx0[79:70];
        regs_regs_slc_regs_regs_2_itm <= regs_regs_1_sva_mx0[69:60];
        regs_regs_slc_regs_regs_2_4_itm <= regs_regs_1_sva_mx0[89:80];
        regs_regs_slc_regs_regs_2_2_itm <= regs_regs_1_sva_mx0[19:10];
        regs_regs_slc_regs_regs_2_3_itm <= regs_regs_1_sva_mx0[9:0];
        regs_regs_slc_regs_regs_2_1_itm <= regs_regs_1_sva_mx0[29:20];
        reg_vout_rsc_mgc_inout_stdreg_en_dout_tmp_1 <= (~ FRAME_slc_1_itm_1) | (res_1_lpi_1_dfm_1_mx0[11]);
        reg_vout_rsc_mgc_inout_stdreg_en_dout_tmp_2 <= FRAME_p_slc_FRAME_p_2_itm_1
            | (res_1_lpi_1_dfm_1_mx0[10]);
        reg_vout_rsc_mgc_inout_stdreg_en_dout_tmp_3 <= res_1_lpi_1_dfm_1_mx0[9:0];
      end
    end
  end

  function [89:0] signext_90_1;
    input [0:0] vector;
  begin
    signext_90_1= {{89{vector[0]}}, vector};
  end
  endfunction


  function [8:0] readslicef_10_9_1;
    input [9:0] vector;
    reg [9:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_10_9_1 = tmp[8:0];
  end
  endfunction


  function [13:0] MUX_v_14_2_2;
    input [27:0] inputs;
    input [0:0] sel;
    reg [13:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[27:14];
      end
      1'b1 : begin
        result = inputs[13:0];
      end
      default : begin
        result = inputs[27:14];
      end
    endcase
    MUX_v_14_2_2 = result;
  end
  endfunction


  function [12:0] MUX_v_13_2_2;
    input [25:0] inputs;
    input [0:0] sel;
    reg [12:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[25:13];
      end
      1'b1 : begin
        result = inputs[12:0];
      end
      default : begin
        result = inputs[25:13];
      end
    endcase
    MUX_v_13_2_2 = result;
  end
  endfunction


  function [0:0] readslicef_15_1_14;
    input [14:0] vector;
    reg [14:0] tmp;
  begin
    tmp = vector >> 14;
    readslicef_15_1_14 = tmp[0:0];
  end
  endfunction


  function [18:0] signext_19_1;
    input [0:0] vector;
  begin
    signext_19_1= {{18{vector[0]}}, vector};
  end
  endfunction


  function [2:0] readslicef_4_3_1;
    input [3:0] vector;
    reg [3:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_4_3_1 = tmp[2:0];
  end
  endfunction


  function [1:0] readslicef_3_2_1;
    input [2:0] vector;
    reg [2:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_3_2_1 = tmp[1:0];
  end
  endfunction


  function [3:0] readslicef_5_4_1;
    input [4:0] vector;
    reg [4:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_5_4_1 = tmp[3:0];
  end
  endfunction


  function [29:0] MUX_v_30_2_2;
    input [59:0] inputs;
    input [0:0] sel;
    reg [29:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[59:30];
      end
      1'b1 : begin
        result = inputs[29:0];
      end
      default : begin
        result = inputs[59:30];
      end
    endcase
    MUX_v_30_2_2 = result;
  end
  endfunction


  function [29:0] signext_30_1;
    input [0:0] vector;
  begin
    signext_30_1= {{29{vector[0]}}, vector};
  end
  endfunction


  function [0:0] readslicef_19_1_18;
    input [18:0] vector;
    reg [18:0] tmp;
  begin
    tmp = vector >> 18;
    readslicef_19_1_18 = tmp[0:0];
  end
  endfunction


  function [6:0] readslicef_8_7_1;
    input [7:0] vector;
    reg [7:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_8_7_1 = tmp[6:0];
  end
  endfunction


  function [4:0] readslicef_6_5_1;
    input [5:0] vector;
    reg [5:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_6_5_1 = tmp[4:0];
  end
  endfunction


  function [1:0] signext_2_1;
    input [0:0] vector;
  begin
    signext_2_1= {{1{vector[0]}}, vector};
  end
  endfunction


  function [7:0] readslicef_9_8_1;
    input [8:0] vector;
    reg [8:0] tmp;
  begin
    tmp = vector >> 1;
    readslicef_9_8_1 = tmp[7:0];
  end
  endfunction


  function [18:0] MUX_v_19_2_2;
    input [37:0] inputs;
    input [0:0] sel;
    reg [18:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[37:19];
      end
      1'b1 : begin
        result = inputs[18:0];
      end
      default : begin
        result = inputs[37:19];
      end
    endcase
    MUX_v_19_2_2 = result;
  end
  endfunction


  function [0:0] MUX_s_1_2_2;
    input [1:0] inputs;
    input [0:0] sel;
    reg [0:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[1:1];
      end
      1'b1 : begin
        result = inputs[0:0];
      end
      default : begin
        result = inputs[1:1];
      end
    endcase
    MUX_s_1_2_2 = result;
  end
  endfunction


  function [89:0] MUX_v_90_2_2;
    input [179:0] inputs;
    input [0:0] sel;
    reg [89:0] result;
  begin
    case (sel)
      1'b0 : begin
        result = inputs[179:90];
      end
      1'b1 : begin
        result = inputs[89:0];
      end
      default : begin
        result = inputs[179:90];
      end
    endcase
    MUX_v_90_2_2 = result;
  end
  endfunction


  function signed [14:0] conv_u2s_14_15 ;
    input [13:0]  vector ;
  begin
    conv_u2s_14_15 = {1'b0, vector};
  end
  endfunction


  function signed [29:0] conv_s2s_15_30 ;
    input signed [14:0]  vector ;
  begin
    conv_s2s_15_30 = {{15{vector[14]}}, vector};
  end
  endfunction


  function signed [13:0] conv_s2s_13_14 ;
    input signed [12:0]  vector ;
  begin
    conv_s2s_13_14 = {vector[12], vector};
  end
  endfunction


  function signed [12:0] conv_u2s_12_13 ;
    input [11:0]  vector ;
  begin
    conv_u2s_12_13 = {1'b0, vector};
  end
  endfunction


  function signed [12:0] conv_s2s_11_13 ;
    input signed [10:0]  vector ;
  begin
    conv_s2s_11_13 = {{2{vector[10]}}, vector};
  end
  endfunction


  function signed [10:0] conv_u2s_10_11 ;
    input [9:0]  vector ;
  begin
    conv_u2s_10_11 = {1'b0, vector};
  end
  endfunction


  function signed [10:0] conv_s2s_9_11 ;
    input signed [8:0]  vector ;
  begin
    conv_s2s_9_11 = {{2{vector[8]}}, vector};
  end
  endfunction


  function signed [9:0] conv_u2s_9_10 ;
    input [8:0]  vector ;
  begin
    conv_u2s_9_10 = {1'b0, vector};
  end
  endfunction


  function signed [9:0] conv_s2s_8_10 ;
    input signed [7:0]  vector ;
  begin
    conv_s2s_8_10 = {{2{vector[7]}}, vector};
  end
  endfunction


  function signed [13:0] conv_u2s_11_14 ;
    input [10:0]  vector ;
  begin
    conv_u2s_11_14 = {{3{1'b0}}, vector};
  end
  endfunction


  function  [9:0] conv_u2u_9_10 ;
    input [8:0]  vector ;
  begin
    conv_u2u_9_10 = {1'b0, vector};
  end
  endfunction


  function signed [14:0] conv_s2s_14_15 ;
    input signed [13:0]  vector ;
  begin
    conv_s2s_14_15 = {vector[13], vector};
  end
  endfunction


  function signed [14:0] conv_u2s_13_15 ;
    input [12:0]  vector ;
  begin
    conv_u2s_13_15 = {{2{1'b0}}, vector};
  end
  endfunction


  function  [14:0] conv_u2u_14_15 ;
    input [13:0]  vector ;
  begin
    conv_u2u_14_15 = {1'b0, vector};
  end
  endfunction


  function  [12:0] conv_u2u_12_13 ;
    input [11:0]  vector ;
  begin
    conv_u2u_12_13 = {1'b0, vector};
  end
  endfunction


  function  [11:0] conv_u2u_11_12 ;
    input [10:0]  vector ;
  begin
    conv_u2u_11_12 = {1'b0, vector};
  end
  endfunction


  function  [10:0] conv_u2u_10_11 ;
    input [9:0]  vector ;
  begin
    conv_u2u_10_11 = {1'b0, vector};
  end
  endfunction


  function  [12:0] conv_u2u_11_13 ;
    input [10:0]  vector ;
  begin
    conv_u2u_11_13 = {{2{1'b0}}, vector};
  end
  endfunction


  function  [3:0] conv_u2u_3_4 ;
    input [2:0]  vector ;
  begin
    conv_u2u_3_4 = {1'b0, vector};
  end
  endfunction


  function  [2:0] conv_u2u_2_3 ;
    input [1:0]  vector ;
  begin
    conv_u2u_2_3 = {1'b0, vector};
  end
  endfunction


  function  [3:0] conv_u2u_2_4 ;
    input [1:0]  vector ;
  begin
    conv_u2u_2_4 = {{2{1'b0}}, vector};
  end
  endfunction


  function signed [2:0] conv_u2s_2_3 ;
    input [1:0]  vector ;
  begin
    conv_u2s_2_3 = {1'b0, vector};
  end
  endfunction


  function signed [5:0] conv_s2s_5_6 ;
    input signed [4:0]  vector ;
  begin
    conv_s2s_5_6 = {vector[4], vector};
  end
  endfunction


  function signed [4:0] conv_u2s_4_5 ;
    input [3:0]  vector ;
  begin
    conv_u2s_4_5 = {1'b0, vector};
  end
  endfunction


  function signed [4:0] conv_u2s_3_5 ;
    input [2:0]  vector ;
  begin
    conv_u2s_3_5 = {{2{1'b0}}, vector};
  end
  endfunction


  function signed [4:0] conv_s2s_3_5 ;
    input signed [2:0]  vector ;
  begin
    conv_s2s_3_5 = {{2{vector[2]}}, vector};
  end
  endfunction


  function  [11:0] conv_u2u_10_12 ;
    input [9:0]  vector ;
  begin
    conv_u2u_10_12 = {{2{1'b0}}, vector};
  end
  endfunction


  function signed [7:0] conv_s2s_6_8 ;
    input signed [5:0]  vector ;
  begin
    conv_s2s_6_8 = {{2{vector[5]}}, vector};
  end
  endfunction


  function  [4:0] conv_u2u_4_5 ;
    input [3:0]  vector ;
  begin
    conv_u2u_4_5 = {1'b0, vector};
  end
  endfunction


  function signed [7:0] conv_u2s_6_8 ;
    input [5:0]  vector ;
  begin
    conv_u2s_6_8 = {{2{1'b0}}, vector};
  end
  endfunction


  function  [5:0] conv_u2u_5_6 ;
    input [4:0]  vector ;
  begin
    conv_u2u_5_6 = {1'b0, vector};
  end
  endfunction


  function  [8:0] conv_u2u_8_9 ;
    input [7:0]  vector ;
  begin
    conv_u2u_8_9 = {1'b0, vector};
  end
  endfunction


  function  [8:0] conv_u2u_7_9 ;
    input [6:0]  vector ;
  begin
    conv_u2u_7_9 = {{2{1'b0}}, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    edge_counter
//  Generated from file(s):
//  644) $PROJECT_HOME/edge_counter.c
//    7) $PROJECT_HOME/shift_class.h
// ------------------------------------------------------------------


module edge_counter (
  vin_rsc_z, vin_rsc_lz, vout_rsc_z, vout_rsc_lzout, vout_rsc_lzin, sum_rsc_z, flag_rsc_z,
      clk, en, arst_n
);
  input [89:0] vin_rsc_z;
  output vin_rsc_lz;
  inout [29:0] vout_rsc_z;
  output vout_rsc_lzout;
  output vout_rsc_lzin;
  output [29:0] sum_rsc_z;
  output flag_rsc_z;
  input clk;
  input en;
  input arst_n;


  // Interconnect Declarations
  wire vin_rsc_mgc_in_wire_en_ld;
  wire [89:0] vin_rsc_mgc_in_wire_en_d;
  wire [29:0] vout_rsc_mgc_inout_stdreg_en_din;
  wire vout_rsc_mgc_inout_stdreg_en_ldout;
  wire [29:0] vout_rsc_mgc_inout_stdreg_en_dout;
  wire [29:0] sum_rsc_mgc_out_stdreg_d;


  // Interconnect Declarations for Component Instantiations 
  mgc_in_wire_en #(.rscid(1),
  .width(90)) vin_rsc_mgc_in_wire_en (
      .ld(vin_rsc_mgc_in_wire_en_ld),
      .d(vin_rsc_mgc_in_wire_en_d),
      .lz(vin_rsc_lz),
      .z(vin_rsc_z)
    );
  mgc_inout_stdreg_en #(.rscid(2),
  .width(30)) vout_rsc_mgc_inout_stdreg_en (
      .ldin(1'b0),
      .din(vout_rsc_mgc_inout_stdreg_en_din),
      .ldout(vout_rsc_mgc_inout_stdreg_en_ldout),
      .dout(vout_rsc_mgc_inout_stdreg_en_dout),
      .lzin(vout_rsc_lzin),
      .lzout(vout_rsc_lzout),
      .z(vout_rsc_z)
    );
  mgc_out_stdreg #(.rscid(3),
  .width(30)) sum_rsc_mgc_out_stdreg (
      .d(sum_rsc_mgc_out_stdreg_d),
      .z(sum_rsc_z)
    );
  mgc_out_stdreg #(.rscid(4),
  .width(1)) flag_rsc_mgc_out_stdreg (
      .d(1'b1),
      .z(flag_rsc_z)
    );
  edge_counter_core edge_counter_core_inst (
      .clk(clk),
      .en(en),
      .arst_n(arst_n),
      .vin_rsc_mgc_in_wire_en_ld(vin_rsc_mgc_in_wire_en_ld),
      .vin_rsc_mgc_in_wire_en_d(vin_rsc_mgc_in_wire_en_d),
      .vout_rsc_mgc_inout_stdreg_en_ldout(vout_rsc_mgc_inout_stdreg_en_ldout),
      .vout_rsc_mgc_inout_stdreg_en_dout(vout_rsc_mgc_inout_stdreg_en_dout),
      .sum_rsc_mgc_out_stdreg_d(sum_rsc_mgc_out_stdreg_d)
    );
endmodule



